spring:
  datasource:
    url: jdbc:h2:mem:paperless;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate.format_sql: true
server:
  port: 0

paperless:
  storage:
    upload-dir: test-uploads