spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paperless
    username: paperless_user
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update     # erstellt automatisch Tabellen, passt sich an Entities an
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  jackson:
    serialization:
      INDENT_OUTPUT: true   # formatiert JSON-Ausgaben sch√∂n
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

  app:
    minio:
      url: ${MINIO_URL:http://minio:9000}
      access-key: ${MINIO_ACCESS_KEY:paperless}
      secret-key: ${MINIO_SECRET_KEY:paperlesssecret}
      bucket: ${MINIO_BUCKET:documents}

# Optional: Server-Port (muss zu Dockerfile passen)
server:
  port: 8081

# Logging
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE