services:
  db:
    image: postgres:16
    container_name: paperless-db
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless_user -d paperless"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [spring-boot-network]

  adminer:
    image: adminer
    ports:
      - "9091:8080"
    depends_on:
      - db
    networks: [spring-boot-network]

  rest-api:
    build: ./backend
    container_name: paperless-rest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paperless
      SPRING_DATASOURCE_USERNAME: paperless_user
      SPRING_DATASOURCE_PASSWORD: secret
      SERVER_PORT: 8081
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    networks: [spring-boot-network]

  frontend:
    build:
      context: ./frontend
    image: paperless-frontend:latest
    # nginx liefert die React-App und proxyt /api â†’ rest-api:8081
    ports:
      - "80:80"
    depends_on:
      - rest-api
    networks: [spring-boot-network]

networks:
  spring-boot-network:
    name: spring-boot-network
    driver: bridge

volumes:
  db_data:
