services:
  db:
    image: postgres:16
    container_name: paperless-db
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless_user -d paperless"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [paperless-net]

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

#  ocr-worker:
#    build: ./OcrWorker
#    container_name: ocr-worker
#    depends_on:
#      - rabbitmq
#    restart: on-failure


  adminer:
    image: adminer
    container_name: paperless-adminer
    ports:
      - "9091:8080"
    depends_on:
      - db
    networks: [paperless-net]

  rest-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: paperless-rest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paperless
      SPRING_DATASOURCE_USERNAME: paperless_user
      SPRING_DATASOURCE_PASSWORD: secret
      SERVER_PORT: 8081
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data/uploads:/app/uploads
    networks: [paperless-net]

  webui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: paperless-webui
    ports:
      - "80:80"          # <— Web UI über Port 80
    depends_on:
      - rest-api
    networks: [paperless-net]

networks:
  paperless-net:
    name: paperless-net
    driver: bridge

volumes:
  db_data:
